import type { Metadata } from "next";
import ReduxProvider from "./ReduxProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Avani Agarwal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
